import = [
	"/home/judasmoses/.config/alacritty/themes/one_dark.toml",
]

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "Hack"
style = "Bold"

[font.normal]
family = "Hack"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 1

[shell]
program = "/sbin/fish"
